import { Router } from "express";
import { createTeacher, listTeachers } from "../controllers/teacher.controller.js";
import { authenticate } from "../middleware/auth.middleware.js";
import { authorize } from "../middleware/authorize.middleware.js";
import { asyncHandler } from "../middleware/asyncHandler.js";
import { validate } from "../middleware/validate.js";
import { createTeacherSchema } from "../validators/teacher.validator.js";
const router = Router();
router.use(authenticate);
router.get("/", authorize("CHAIRMAN", "COMMITTEE_CHAIRMAN"), asyncHandler(listTeachers));
router.post("/", authorize("CHAIRMAN"), validate(createTeacherSchema), asyncHandler(createTeacher));
export default router;
