import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import rateLimit from "express-rate-limit";
import authRoutes from "./routes/auth.routes.js";
import teacherRoutes from "./routes/teacher.routes.js";
import examRoutes from "./routes/exam.routes.js";
import committeeRoutes from "./routes/committee.routes.js";
import routineRoutes from "./routes/routine.routes.js";
import proceedingsRoutes from "./routes/proceedings.routes.js";
import remunerationRoutes from "./routes/remuneration.routes.js";
import notificationRoutes from "./routes/notification.routes.js";
import { notFound, errorHandler } from "./middleware/error.middleware.js";

const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL, credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
app.use("/api/v1", rateLimit({ windowMs: 15 * 60 * 1000, limit: 300 }));
app.get("/api/v1/health", (req, res) => res.json({ success: true, message: "API is running" }));
app.use("/api/v1/auth", authRoutes);
app.use("/api/v1/teachers", teacherRoutes);
app.use("/api/v1/exams", examRoutes);
app.use("/api/v1/committees", committeeRoutes);
app.use("/api/v1/routines", routineRoutes);
app.use("/api/v1/proceedings", proceedingsRoutes);
app.use("/api/v1/remunerations", remunerationRoutes);
app.use("/api/v1/notifications", notificationRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
